### ISSUE TITLE
Request for Clarification: Fiat Account Endpoint 

### ISSUE THREAD

**Issue by matabeitt** [fiatconnect/specification#25]
Regarding this section of the specification for `Fiat Account Endpoints`:
https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#333-fiat-account-endpoints

This part of the spec indicates the following endpoints as part of the standard:

`POST /accounts/:fiatAccountSchema`
`GET /accounts`
`DELETE /account/:fiatAccountId`

Could it be confirmed whether or not the endpoints should be unified under a singular path, or whether having `account` and `accounts` is intentional?

**Comment by cajubelt** [comment]
@matabeitt it is not intentional, to my knowledge. Feel free to submit a PR to consolidate the paths, seems reasonable to me

**Comment by rafapolo** [comment]
Not sure if there is a consensus on resources being plural or singular, but Google, [on their API design guide](https://cloud.google.com/apis/design/resource_names), says a proper URI patterns for resource-oriented APIs applications would follow the plural and deal with the distinct HTTP verbs. So, I would vote for,

`
DELETE /accounts/:fiatAccountId
`

**Comment by matabeitt** [comment]
In my experience plural is more prevalent, but the other endpoints in this spec use singular. KYC is a noun with no suitable plural, and can remain singular.

However, I do agree that the endpoints (accounts, quotes, transfers) should be pluralized.
