### ISSUE TITLE
Invalid swagger 

### ISSUE THREAD

**Issue by andreujuanc** [fiatconnect/specification#48]
Hi, 

I have validated the swagger file in several places and all showing the same error.
Even the repo's `validate` script fails with the following:

``` bash
yarn
yarn validate
```

``` bash
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//accounts/{fiatAccountSchema}/post/parameters/1
    Data does not match any schemas from 'oneOf' at #/paths//accounts/{fiatAccountSchema}/post/parameters/1
      Missing required property: schema at #/
      Missing required property: type at #/
    Missing required property: $ref at #/paths//accounts/{fiatAccountSchema}/post/parameters/1
 
JSON_OBJECT_VALIDATION_FAILED
```

Using:
- Node: 16.14.2
- v1.22.18
- Docker container Dockerfile `FROM node:16`

**Comment by MuckT** [comment]
@andreujuanc the repo's swagger is currently invalid; however,  [Swagger spec enums and equivalent paths #40](https://github.com/fiatconnect/specification/pull/40) should fix.

**Comment by MuckT** [comment]
@andreujuanc this should be fixed now.

**Comment by andreujuanc** [comment]
@MuckT  can confirm!! Well done.
