### ISSUE TITLE
/quote params

### ISSUE THREAD

**Issue by andreujuanc** [fiatconnect/specification#53]
Very cool that the swagger is valid now, but there is still an issue.
The `/quote/in` and `/quote/out` endpoints have defined bodies, but that data should be actually a query param as per the spec https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#34111-parameters

The following image shows the params being required in body:
![image](https://user-images.githubusercontent.com/360052/170590999-b4f5de3e-84da-448d-996f-98b9316d24f6.png)

Here are the culprits:
- https://github.com/fiatconnect/specification/blob/main/swagger.yaml#L344
- https://github.com/fiatconnect/specification/blob/main/swagger.yaml#L371

**Comment by cajubelt** [comment]
quote endpoints are POST now so this appears to be outdated
